include ../mk.d/all.mk

include conf.mk

include ../mk.d/colors.mk
include ../mk.d/functions.mk
include ../mk.d/sources.mk
include ../mk.d/dependencies.mk
include ../mk.d/patch.mk
include ../mk.d/toplevel.mk
include ../mk.d/remote.mk
include ../mk.d/production.mk
include ../mk.d/qemu.mk
